### ISSUE TITLE
IPaddr2: arping support and refactroing

### ISSUE THREAD

**Issue by kskmori** [kskmori/resource-agents#6]
This series of patches is to fix a bunch of issues related to send_arp (__Known issues:__ below) as well as to support `arping` command instead of send_arp.
This pull request should not change any behavior for the existing configuration (except for bug fixes).

### Known issues: ###
* need an option for  sending ARP REPLY (`arping -A`) 
  -  some switches does not accept ARP REQUEST(arping -U, send_arp) but do only ARP REPLY (arping -A)
* send_arp: arp_interval does not work
  - http://lists.clusterlabs.org/pipermail/users/2016-October/004180.html
* send_arp: src_hw_addr, broadcast_ip_addr, and netmask are not set properly which causes clusterip unavailable
  - ​https://github.com/ClusterLabs/resource-agents/issues/860
* send_arp: improper documentation
  - https://github.com/ClusterLabs/resource-agents/issues/860
* IPaddr2: arp_mac is no longer in use but still described in the metadata
  - removed with the commit 2852f51 and 0295fa1
* an output from send_arp is not logged when run in a background

### Proposals to fix: ###
* extend `arp_sender` parameter to allow to choose the standard arping bundled in the distro. 
  - aims to replace send_arp binary with arping as default in the future
  - also considering a variant of arping command (iputils_arping, libnet_arping)
* add a new `send_arp_opts` parameter 
  - allow to send ARP REPLY instead of ARP REQUEST
* send_arp.{libnet, linux} are left only for the backward compatibility with minimal changes
  - basically fixes documentation errors only
  - the usage of send_arp.linux shows options that are currently used as a drop-in replacement of send_arp.libnet
* let `arp_interval` parameter as deprecated and document it
  - it does not seem to be used frequently and only limited tools support it
* do not send gratuitous ARPs in the Cluster IP configuration
  - it does not seem to be necessary because the cluster MAC will not change and nothing needs to be updated on the peers (point me if it's wrong)
  - sending a physical MAC does cause a problem 
* use ocf_log for the output from send_arp command

### Related duscussion: ###
* The great summary of the history by lge
  - ​https://github.com/ClusterLabs/resource-agents/issues/860#issuecomment-263335126
* suggestion of replacing send_arp with arping
  - https://lists.gt.net/linuxha/pacemaker/58110#58110
  - https://github.com/ClusterLabs/resource-agents/issues/860#issuecomment-263335126
  - https://github.com/ClusterLabs/resource-agents/pull/654#issuecomment-128015953
* Why send_arp use ARP_REQUEST
  - https://lists.gt.net/linuxha/pacemaker/58444#58444

### Implementation notes: ###
* Debian has two flavor of arping which are not compatible options each other. iputils-arping is equivalent to the one in RHEL/SUSE .
  - iputils-arping : https://packages.debian.org/sid/iputils-arping
  - arping : https://packages.debian.org/sid/arping
    * refers as 'libnet-arping' in this article to avoid confusing

### Comparison: iputils-arping vs. libnet-arping ###

Options / Exit code | iputils | libnet | memo
--------------------|---------|--------|-------
*Options* |  |  | 
Unsolicited (ARP_REQUEST) | -U | -U -S | libnet: -S is necessary for Gratuitous ARP
Unsolicited (ARP_REPLY)   | -A | -P -U -S | iputils: having both -A and -U also works  <br /> libnet: -A has a different meaning
ARP interval | N.A. | -w | iputils: -w is a total timeout
ARP count | -c | -c |
Source MAC address | N.A. | -p -s |  libnet: can not usable for Cluster IP anyway; can not be seen on the peers with Multicast MAC as a source(note 1)
Interface | -I | -i | 
*Exit code* |  |  | 
success for Unsolicited | 0 | 1(-U) / <br /> 0 (-P -U) | libnet: always error as no response with -U
no response | 1 | 1 |
error (bad option) | 2 | 1 |
*misc.* | | |
extra dependency | - | libnet |

* (note 1): difference between send_arp.libnet macaddr vs. libnet-arping -s macaddr
  - send_arp.libnet: Ethernet src=HW MAC, ARP Sender MAC=macaddr
  - libnet-arping -s: Ethernet src=macaddr, ARP Sender MAC=macaddr

### Development branch ###
* https://github.com/ClusterLabs/resource-agents/compare/master...kskmori:devel-IPaddr2-refactor
  - development history
* https://github.com/ClusterLabs/resource-agents/compare/master...kskmori:devel-IPaddr2-refactor-2
  - reorganized branch for the pull request preparetion
  - may be forced update without notices
  - the results should be identical to the above

### Test Cases ###
* https://docs.google.com/spreadsheets/d/1fJsnIhBm0DCCWkZ8sdqHriZPiOKEDXru3fgR_LTtjoE/edit?usp=sharing

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/961

**Comment by kskmori** [comment]
Closed as https://github.com/ClusterLabs/resource-agents/pull/977 was merged.
